wip
gam6itko/go-musthave-diploma pull request #1
Opened 2024-02-25 12:12 UTC by gam6itko

2024-02-28 13:38 UTC, tmvrus requested changes
а где тесты?

2024-02-28 14:54 UTC, gam6itko commented
@tmvrus  Я особо их не писал. Ориентировался на автотесты из другого проекта. Это критично? Сколько нужно добавить?

2024-02-28 15:03 UTC, tmvrus commented
> @tmvrus Я особо их не писал. Ориентировался на автотесты из другого проекта. Это критично? Сколько нужно добавить?

как минимум продемонстрировать что ты умеешь их писать, поскольку соответствующая тема была в курсе

2024-02-28 15:47 UTC, gam6itko commented
@tmvrus Ок, добавлю.

2024-03-16 18:10 UTC, gam6itko commented
@tmvrus Обильно снабдил код интерфейсами. Добавил тестов на контроллеры.

2024-03-16 20:25 UTC, tmvrus approved these changes
сойдет

2024-03-16 20:25 UTC, tmvrus commented on cmd/gophermart/app_config.go
> +		log.Print(err)
А какая цель менять Fatal на Print?
раньше, при ошибке работа системы завершалась, сейчас сервис продолжит работать

2024-03-16 20:25 UTC, tmvrus commented on internal/repository/WithdrawalRepository.go
> +func (ths WithdrawalRepository) rowsToOrders(rows *sql.Rows) ([]*diploma.Withdrawal, error) {
этой функции не обязательно привязываться к WithdrawalRepository она ничего оттуда не использует

2024-03-16 20:25 UTC, tmvrus commented on internal/repository/WithdrawalRepository.go
> +func (ths WithdrawalRepository) FindByUserID(ctx context.Context, userID uint64) ([]*diploma.Withdrawal, error) {
нет смысла возвращать слайс ссылок []*diploma.Withdrawal, тут вполне бы подошел []diploma.Withdrawal

2024-03-16 20:25 UTC, tmvrus commented on internal/repository/UserRepository.go
> +	tx, err := ths.db.BeginTx(ctx, nil)
эта транзакция гарантирует только сохранение операции, но не гарантирует что balance_current не станет отрицательным

2024-03-16 20:25 UTC, tmvrus commented on internal/controller/main.go
не стоит так называть файлы, если она не содержат ф-ю main
это сбивает с толку, поскольку обычно так не поступают

2024-03-16 20:25 UTC, tmvrus commented on internal/controller/AnonController.go
> +	userID, err := ths.userRepo.InsertNew(r.Context(), *l.Login, string(hashPass))
никаких гарантий, что между проверкой и вставкой не будет сохранен пользователь из парралельного запроса, база никак не гарантирует уникальность логина, хотя могла бы

2024-03-16 20:56 UTC, gam6itko commented on internal/repository/WithdrawalRepository.go
> +func (ths WithdrawalRepository) FindByUserID(ctx context.Context, userID uint64) ([]*diploma.Withdrawal, error) {
Потому что этот результат используется только для серелищации?

2024-03-17 07:21 UTC, gam6itko commented on cmd/gophermart/app_config.go
> +		log.Print(err)
тут я использую `godotenv.Load()` чтобы на локальной машине грузить ENV из файла. На тестовом стенде такого файла нет, а ENV указываются перед запуском теста. Программа нед должна упасть если такого файла нет.

2024-03-17 07:27 UTC, merged

2024-03-17 07:29 UTC, gam6itko commented on internal/repository/WithdrawalRepository.go
> +func (ths WithdrawalRepository) rowsToOrders(rows *sql.Rows) ([]*diploma.Withdrawal, error) {
Задумка была в том, что эта функция нужна лишь этому классу. В OrderRepository есть метод с похожим названием. Если отвязать от класса, то они будут конфликтовать.

2024-03-17 19:16 UTC, tmvrus commented on internal/repository/WithdrawalRepository.go
> +func (ths WithdrawalRepository) FindByUserID(ctx context.Context, userID uint64) ([]*diploma.Withdrawal, error) {
потому что
- слайс сам по себе ссылочный тип
- никакой дополнительно пользы от вычисления ссылке тут нет

С сериализацией это никак не связано

2024-03-17 19:17 UTC, tmvrus commented on internal/repository/WithdrawalRepository.go
> +func (ths WithdrawalRepository) rowsToOrders(rows *sql.Rows) ([]*diploma.Withdrawal, error) {
может в таком случае назвать ф-ю более явным образом, что бы не было конфликта ?